# Generated by Django 2.1.5 on 2019-02-01 09:54

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='upload/furniture')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('used_period', models.CharField(max_length=100)),
                ('is_negotiable', models.BooleanField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_like_new', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='upload/space')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_negotiable', models.BooleanField()),
                ('is_expired', models.BooleanField(default=False)),
                ('facility', multiselectfield.db.fields.MultiSelectField(choices=[('24 hr WATER', '24 hr WATER'), ('NEAR ROAD', 'NEAR ROAD'), ('TRANSPORTATION', 'TRANSPORTATION'), ('INTERNET', 'INTERNET'), ('HOT WATER', 'HOT WATER'), ('SECURITY GUARD', 'SECURITY GUARD'), ('CAR PARKING SPACE', 'CAR PARKING SPACE'), ('BIKE PARKING SPACE', 'BIKE PARKING SPACE')], max_length=107)),
            ],
        ),
    ]
