# Generated by Django 2.1.5 on 2019-01-30 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='furniture')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('used_period', models.CharField(max_length=100)),
                ('is_negotiable', models.BooleanField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_like_new', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='space')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_negotiable', models.BooleanField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='store.Space'),
        ),
    ]
