# Generated by Django 2.1.5 on 2019-02-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='space',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='furniture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furniture_images', to='store.Furniture'),
        ),
        migrations.AddField(
            model_name='image',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_images', to='store.Space'),
        ),
    ]
